services:
  - type: web
    name: whisper-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    runtime: python-3.10
    plan: free

